ly:
  jwt:
    secret: ly@Login(Auth}*^31)&heiMa% # 登录校验的密钥
    pubKeyPath: E:\\tmp\\rsa\\rsa.pub # 公钥地址
    priKeyPath: E:\\tmp\\rsa\\rsa.pri # 私钥地址
    expire: 30 # 过期时间,单位分钟
    cookieMaxAge: 18000
    cookieName: LY_TOKEN