server:
  port: 8080
#spring.data.mongodb.uri=mongodb://127.0.0.1:27017/test
#设置了密码
spring:
  data:
    mongodb:
      host: 192.168.253.129
      port: 27017
      authentication-database: admin
      database: test
      username: root
      password: '123456' #注意是字符形式